### ISSUE TITLE
Issue with Cross Container builder - Pip install broken

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#547] opened 2021-02-16 07:31 UTC
### What happened?
Issue while building cross container , the new pip version has some incompatibility with the python version
```
Step 3/17 : RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&     python get-pip.py &&     pip install awscli --upgrade
 ---> Running in 3dbdc8683f65
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1884k  100 1884k    0     0  3886k      0 --:--:-- --:--:-- --:--:-- 3885k
Traceback (most recent call last):
  File "get-pip.py", line 24244, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpsSR3bk/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

### How can we reproduce it?

Run build/run make -j4

### What environment did it happen in?
Crossplane version: provider-aws:latest

**Comment by muvaf** [comment] 2021-02-16 08:20
Could you share more steps for reproducing? I don't really know where we use Python.

**Comment by jbw976** [comment] 2021-02-16 16:39
@muvaf this looks like something that @rbwsam fixed in the upstream build submodule recently: https://github.com/upbound/build/pull/133

I think that if we were to update build submodule in this repo, then this would be resolved 🙏

**Comment by muvaf** [comment] 2021-02-16 18:22
@jbw976 thanks for noticing! Opened a PR to update it.

**Closed** 2021-02-16 20:22 UTC
Labels: bug
