### ISSUE TITLE
InvalidParameterCombination when creating a ReplicationGroup

### ISSUE THREAD

**Issue by ciaranRoche** [crossplane/provider-aws#326] opened 2020-09-02 15:11 UTC
### What happened?

Error when creating a Replication Group
```
"create failed: cannot create ElastiCache replication group: InvalidParameterCombination: Use of cache security groups is not permitted along with cache subnet group and/or security group Ids.\n\tstatus code: 400, request id: 7524deef-ec04-4428-87d1-8124bffe0f9c"
```

The full CR
```
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
  annotations:
    crossplane.io/external-name: mase-cache
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"cache.aws.crossplane.io/v1beta1","kind":"ReplicationGroup","metadata":{"annotations":{},"labels":{"example":"true"},"name":"mase-cache","namespace":""},"spec":{"forProvider":{"applyModificationsImmediately":true,"automaticFailoverEnabled":true,"cacheNodeType":"cache.t3.medium","cacheParameterGroupName":"default.redis5.0","cacheSecurityGroupNameRefs":[{"name":"mase-cluster-sg"}],"cacheSubnetGroupName":"mase-elasticache-sg","engine":"redis","engineVersion":"5.0.6","numCacheClusters":2,"port":6379,"replicationGroupDescription":"a
      mase replication group provisioned by
      crossplane"},"providerRef":{"name":"aws-provider"},"reclaimPolicy":"Delete","writeConnectionSecretToRef":{"name":"redis-conn","namespace":"crossplane"}}}
  selfLink: /apis/cache.aws.crossplane.io/v1beta1/replicationgroups/mase-cache
  resourceVersion: '809951'
  name: mase-cache
  uid: 04211f10-054f-4027-b127-fe72b9686946
  creationTimestamp: '2020-09-01T16:33:28Z'
  generation: 3
  finalizers:
    - finalizer.managedresource.crossplane.io
  labels:
    example: 'true'
spec:
  forProvider:
    port: 6379
    engine: redis
    cacheParameterGroupName: default.redis5.0
    automaticFailoverEnabled: true
    cacheSecurityGroupNameRefs:
      - name: mase-cluster-sg
    replicationGroupDescription: a mase replication group provisioned by crossplane
    cacheSecurityGroupNames:
      - mase-cluster-sg
    cacheSubnetGroupName: mase-elasticache-sg
    numCacheClusters: 2
    applyModificationsImmediately: true
    engineVersion: 5.0.6
    tags:
      - key: crossplane-kind
        value: replicationgroup.cache.aws.crossplane.io
      - key: crossplane-name
        value: mase-cache
      - key: crossplane-provider
        value: aws-provider
    cacheNodeType: cache.t3.medium
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: redis-conn
    namespace: crossplane
status:
  atProvider:
    configurationEndpoint: {}
    pendingModifiedValues:
      resharding:
        slotMigration:
          progressPercentage: 0
  conditions:
    - lastTransitionTime: '2020-09-01T16:33:28Z'
      reason: Resource is being created
      status: 'False'
      type: Ready
    - lastTransitionTime: '2020-09-01T16:45:25Z'
      message: "create failed: cannot create ElastiCache replication group: InvalidParameterCombination: Use of cache security groups is not permitted along with cache subnet group and/or security group Ids.\n\tstatus code: 400, request id: 7524deef-ec04-4428-87d1-8124bffe0f9c"
      reason: Encountered an error during resource reconciliation
      status: 'False'
      type: Synced
```

We have verified using the params specified in the CR, we can create a replication group manually via the AWS-CLI.
If we remove the `cacheSecurityGroupNameRefs` from the CR it creates okay, we can then manually add the security group via the AWS console

### How can we reproduce it?

- Create a VPC 
- Create a Security Group
- Create two Subnets
- Create an Elasticache Subnet Group with two Subnets
- Manually Peer VPC to cluster VPC
- Create Elasticache Replication Group via CR above

## What environment did it happen in?
Crossplane version: 0.11.0 (installed via Operator Hub) 
Openshift version: 4.4.16
Cloud Provider: aws

**Comment by krishchow** [comment] 2020-09-23 15:43
I don't believe this is a bug w/ Crossplane or the AWS Provider - rather this is the intended behavior for the AWS API. ElastiCache does not allow you to create a ReplicationGroup that uses both a _ElastiCache Security Group_ (i.e., cacheSecurityGroupNames) and a _Cache Subnet Group_ (i.e., cacheSubnetGroupNames). This is because ElastiCache Security Groups are specifically meant for older, non-VPC deployments, whereas Subnet Groups are specifically for when you are using a VPC. 

Instead, what I believe you should be using is _VPC Security Groups_ (securityGroupIDs in the CR).

**Comment by muvaf** [comment] 2020-09-30 10:08
I think @krishchow 's assessment is true. Here is an excerpt from [API reference](https://doc.crds.dev/github.com/crossplane/provider-aws/cache.aws.crossplane.io/ReplicationGroup/v1beta1#spec-forProvider-cacheSecurityGroupNames):

> CacheSecurityGroupNames specifies a list of cache security group names to associate with this replication group. Only for EC2-Classic mode.

[EC2-Classic](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html) means you cannot use your own VPC and its subnet in the configuration. I'm closing the issue, feel free to reopen.

**Closed by muvaf** 2020-09-30 10:08 UTC
Labels: bug
